### ISSUE TITLE
Wound Terminal 

### ISSUE THREAD

**Issue by Mifie89** [Thrax989/The-Phoenix-Realm#1]
Disregard

**Comment by Thrax989** [comment]
No worries what did you find?

**Comment by Mifie89** [comment]
At first I though the wound terminal was pulling from the credit balance without checking player distance terminal and not applying buffs. Turns out I was just attempting to apply buffs while already buffs. This could be considered a bug, as it will take the 10k credits, and no effect for the player as it will not clear/reapply buffs. Was going to look into possibly getting buff status, and stop the deduction of credits if already buffed.

**Comment by Thrax989** [comment]
You can take a look at the call it reads from .
MMOCoreORB/src/server/zone/managers/player/PlayerManagerImplementation.cpp

 	// Credits For Buffs
 +	if (player->getCashCredits() < 10000){
  		player->sendSystemMessage("Sorry, you don't have enough cash on hand to purchase a buff.");
  		return;
 +	} else if (player->getCashCredits() >= 10000){
  		// Charge player for buffs
 +		player->subtractCashCredits(10000);
